import os
import re
import json
from typing import List, Dict, Any, Tuple, Optional
try:
    from multilevelsquiz.src.config import config
    from multilevelsquiz.src.audio_generator import (
        ensure_all_sound_effects,
        generate_chinese_voice
    )
except ImportError:
    from src.config import config
    from src.audio_generator import (
        ensure_all_sound_effects,
        generate_chinese_voice
    )

def generate_scene_code(
    levels: List[Dict[str, Any]],
    concept_name: str = "TỨC GIẬN / NỔI CÁU",
    hook_title: str = "5 CẤP ĐỘ 'TỨC GIẬN' TRONG TIẾNG TRUNG",
    scene_name: str = "MultilevelsQuizScene",
    cover_path: str = "",
    cta_text: str = ""
) -> str:
    """
    Generates standalone Python/Manim script code for Multilevels Quiz (1 Nghĩa - 5 Cấp độ HSK):
    - Layout: Khung chữ chủ đề (Mode Card) và Khung 5 dòng HSK được phân tách rõ ràng, tuyệt đối không bị đè lên nhau.
    - Gamification Timing:
      * Sau khi chạy cover: Có ĐÚNG 5 giây đếm ngược (5➔4➔3➔2➔1 kèm tiếng TICK) để người xem suy nghĩ từ HSK 1.
      * Hết 5 giây: Chuông DING mở khóa đáp án HSK 1.
      * Tuần tự lặp lại 5s đếm ngược cho HSK 2, 3, 4, 5.
    - HSK Rows: Dày dặn (height=1.42), chữ to rõ nét.
    - Layout revealed: Nửa bên trái (Chữ Hán trên, Pinyin dưới) | Nửa bên phải (Nghĩa tiếng Việt vàng tươi).
    - Countdown Section: Hạ thấp (Number at DOWN*4.15, Bar at DOWN*4.95, Footer at DOWN*5.75).
    - Header: Bỏ chữ 'Chủ đề:', hiển thị trực tiếp ý niệm cốt lõi.
    - Audio: 100% không có giọng đọc tiếng Việt.
    - Outro: Xóa sạch 100% tất cả khung cũ (self.clear()), chỉ hiện End Card 'BẠN ĐANG Ở HSK NÀO?'.
    """
    clean_concept = concept_name.replace('"', '\\"')
    clean_hook = hook_title.replace('"', '\\"')

    # Pre-generate TTS for Chinese words only (NO Vietnamese TTS)
    levels_data = []
    for item in levels[:5]:
        lvl_num = int(item.get("level", 1))
        hz = str(item.get("hanzi", "")).strip()
        py = str(item.get("pinyin", "")).strip()
        hv = str(item.get("han_viet", "")).strip()
        mean = str(item.get("meaning_vi", "")).strip()
        nuance = str(item.get("nuance_note", "")).strip()
        visual = str(item.get("visual_action", "")).strip()

        voice_path = generate_chinese_voice(hz) if hz else ""
        levels_data.append({
            "level": lvl_num,
            "hanzi": hz,
            "pinyin": py,
            "han_viet": hv,
            "meaning_vi": mean,
            "nuance_note": nuance,
            "visual_action": visual,
            "voice": voice_path
        })

    levels_code = repr(levels_data)

    code = f'''# Auto-generated by lelehoctiengtrung multilevelsquiz scene generator
from manim import *
import os

config.pixel_width = 1080
config.pixel_height = 1920
config.frame_width = 9.0
config.frame_height = 16.0

CHINESE_FONT = "{config.chinese_font}"
VIETNAMESE_FONT = "{config.vietnamese_font}"

BOLD = "BOLD"
SEMIBOLD = "SEMIBOLD"
NORMAL = "NORMAL"

LEVEL_COLORS = {config.level_colors}

LEVEL_TITLES = [
    ("HSK 1", "#10b981"),
    ("HSK 2", "#06b6d4"),
    ("HSK 3", "#3b82f6"),
    ("HSK 4", "#f59e0b"),
    ("HSK 5", "#ef4444")
]

class {scene_name}(Scene):
    def construct(self):
        levels = {levels_code}
        concept_title = "{clean_concept}"
        hook_title = "{clean_hook}"

        # 0. Cover Thumbnail (0.75s Cover at 00:00 for TikTok / Shorts / Reels)
        cover_path = "{cover_path}"
        if os.path.exists(cover_path):
            cover_img = ImageMobject(cover_path)
            cover_img.set_height(config.frame_height)
            cover_img.set_width(config.frame_width)
            self.add(cover_img)
            self.wait(0.75)
            self.remove(cover_img)

        # ---------------------------------------------------------------------
        # 1. TOP HEADER ZONE (TikTok Safe Area: UP * 6.6 to UP * 5.3)
        # ---------------------------------------------------------------------
        # Top Pill: "1 NGHĨA - 5 CẤP ĐỘ"
        pill_text = Text(
            "1 NGHĨA - 5 CẤP ĐỘ",
            font=VIETNAMESE_FONT,
            font_size=24,
            color="#0f172a",
            weight=BOLD
        )
        pill_bg = RoundedRectangle(
            corner_radius=0.28,
            width=max(pill_text.width + 0.8, 5.2),
            height=0.62,
            fill_color="#f59e0b",
            fill_opacity=1.0,
            stroke_color="#fbbf24",
            stroke_width=1.2
        ).move_to(UP * 6.55)
        pill_text.move_to(pill_bg.get_center())
        header_pill = VGroup(pill_bg, pill_text)

        # Concept Box: Trực tiếp hiển thị nghĩa chính (BỎ CHỮ 'Chủ đề:', không đè lên khung HSK)
        mode_card = RoundedRectangle(
            corner_radius=0.24,
            width=7.8,
            height=0.76,
            fill_color="#0f172a",
            fill_opacity=0.98,
            stroke_color="#818cf8",
            stroke_width=1.8
        ).move_to(UP * 5.65)

        mode_title = Text(
            concept_title.upper(),
            font=VIETNAMESE_FONT,
            font_size=28,
            color="#fde047",
            weight=BOLD
        ).move_to(mode_card.get_center())
        if mode_title.width > 7.2:
            mode_title.scale_to_fit_width(7.2)

        header_group = VGroup(header_pill, mode_card, mode_title)
        self.play(FadeIn(header_group, shift=DOWN*0.25), run_time=0.35)

        # ---------------------------------------------------------------------
        # 2. CENTRAL 5-ROW CONTAINER (TÁCH BIỆT RÕ RÀNG VỚI HEADER TRÊN)
        # ---------------------------------------------------------------------
        main_frame = RoundedRectangle(
            corner_radius=0.35,
            width=7.8,
            height=8.4,
            fill_color="#0b0f19",
            fill_opacity=0.96,
            stroke_color="#334155",
            stroke_width=1.8
        ).move_to(UP * 0.70)
        self.play(FadeIn(main_frame, shift=UP*0.2), run_time=0.3)

        # 5 Row Y Positions (Tách biệt hoàn toàn, khoảng cách 1.55 đơn vị)
        row_y_positions = [
            UP * 3.80,  # Row 1 (HSK 1)
            UP * 2.25,  # Row 2 (HSK 2)
            UP * 0.70,  # Row 3 (HSK 3)
            DOWN * 0.85,# Row 4 (HSK 4)
            DOWN * 2.40 # Row 5 (HSK 5 Boss)
        ]

        # Initial Placeholder Rows: Centered [HSK 1] .. [HSK 5] Badges (Dày height=1.42)
        placeholder_rows = []
        for i in range(5):
            lvl_name, _ = LEVEL_TITLES[i]
            y_pos = row_y_positions[i]

            row_card = RoundedRectangle(
                corner_radius=0.22,
                width=7.4,
                height=1.42,
                fill_color="#111827",
                fill_opacity=0.98,
                stroke_color="#1f2937",
                stroke_width=1.5
            ).move_to(y_pos)

            # Center Badge: [HSK 1] .. [HSK 5]
            badge_bg = RoundedRectangle(
                corner_radius=0.16,
                width=2.4,
                height=0.62,
                fill_color="#1e293b",
                fill_opacity=1.0,
                stroke_color="#475569",
                stroke_width=1.4
            ).move_to(row_card.get_center())

            badge_txt = Text(
                lvl_name,
                font=VIETNAMESE_FONT,
                font_size=26,
                color="#cbd5e1",
                weight=BOLD
            ).move_to(badge_bg.get_center())
            badge_grp = VGroup(badge_bg, badge_txt)

            p_row = VGroup(row_card, badge_grp)
            placeholder_rows.append(p_row)

        all_placeholders = VGroup(*placeholder_rows)
        self.play(FadeIn(all_placeholders, lag_ratio=0.06), run_time=0.4)

        # ---------------------------------------------------------------------
        # 3. BOTTOM COUNTDOWN BOX & FOOTER (HẠ THẤP XUỐNG DƯỚI)
        # ---------------------------------------------------------------------
        # Dynamic Countdown Number (Số đếm giây: 5 -> 1)
        timer_num = Text(
            "5",
            font=VIETNAMESE_FONT,
            font_size=50,
            color="#10b981",
            weight=BOLD
        ).move_to(DOWN * 4.15)

        # Countdown Track Bar
        track_bar_width = 7.4
        countdown_track = RoundedRectangle(
            corner_radius=0.1,
            width=track_bar_width,
            height=0.22,
            fill_color="#1e293b",
            fill_opacity=1.0,
            stroke_width=0
        ).move_to(DOWN * 4.95)

        # Bottom Footer: "lelehoctiengtrung"
        footer_logo_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        footer_title = Text(
            "lelehoctiengtrung",
            font=VIETNAMESE_FONT,
            font_size=26,
            color="#94a3b8",
            weight=BOLD
        )
        if os.path.exists(footer_logo_path):
            footer_logo = ImageMobject(footer_logo_path).set_height(0.45)
            footer_group = Group(footer_logo, footer_title).arrange(RIGHT, buff=0.18).move_to(DOWN * 5.75)
        else:
            footer_dot = Dot(radius=0.16, color="#818cf8")
            footer_group = VGroup(footer_dot, footer_title).arrange(RIGHT, buff=0.18).move_to(DOWN * 5.75)

        self.play(
            FadeIn(timer_num),
            FadeIn(countdown_track),
            FadeIn(footer_group),
            run_time=0.3
        )

        tick_sound_file = "{os.path.join(config.base_dir, 'assets/audio/tick.mp3')}"
        bell_sound_file = "{config.ding_audio_path}"
        active_bar = None

        # ---------------------------------------------------------------------
        # 4. PROGRESSIVE 5-LEVEL REVEAL LOOP (ĐẾM NGƯỢC 5S THỬ THÁCH MỖI LEVEL RỒI MỚI REVEAL)
        # ---------------------------------------------------------------------
        for idx, lvl_info in enumerate(levels, start=1):
            lvl_name, lvl_color = LEVEL_TITLES[idx - 1]
            y_pos = row_y_positions[idx - 1]
            hanzi = lvl_info.get("hanzi", "")
            pinyin = lvl_info.get("pinyin", "")
            meaning_vi = lvl_info.get("meaning_vi", "")
            voice_file = lvl_info.get("voice", "")

            # --- GIAI ĐOẠN 1: 5 GIÂY ĐẾM NGƯỢC THỬ THÁCH (Ô HSK ĐANG ĐỐ NHẤP NHÁY Ô CHỜ) ---
            if active_bar is not None:
                self.remove(active_bar)

            active_bar = RoundedRectangle(
                corner_radius=0.1,
                width=track_bar_width,
                height=0.22,
                fill_color=lvl_color,
                fill_opacity=1.0,
                stroke_width=0
            ).move_to(countdown_track.get_center())
            self.add(active_bar)

            current_placeholder = placeholder_rows[idx - 1]
            p_card = current_placeholder[0]

            # Chạy đúng 5 giây đếm ngược (5 -> 4 -> 3 -> 2 -> 1) kèm tiếng TICK mỗi giây
            for sec in range(5, 0, -1):
                if os.path.exists(tick_sound_file):
                    try: self.add_sound(tick_sound_file)
                    except Exception: pass

                new_num = Text(
                    str(sec),
                    font=VIETNAMESE_FONT,
                    font_size=50,
                    color=lvl_color,
                    weight=BOLD
                ).move_to(DOWN * 4.15)

                target_w = max(0.01, track_bar_width * ((sec - 1) / 5.0))
                shrink_step_bar = RoundedRectangle(
                    corner_radius=0.1,
                    width=target_w,
                    height=0.22,
                    fill_color=lvl_color,
                    fill_opacity=1.0 if sec > 1 else 0.0,
                    stroke_width=0
                ).move_to(countdown_track.get_center()).align_to(countdown_track, LEFT)

                pulse_stroke = 3.8 if sec % 2 == 1 else 1.8
                self.play(
                    Transform(timer_num, new_num),
                    Transform(active_bar, shrink_step_bar),
                    p_card.animate.set_stroke(color=lvl_color, width=pulse_stroke),
                    run_time=0.95,
                    rate_func=linear
                )
                self.wait(0.05)

            # --- GIAI ĐOẠN 2: HẾT 5 GIÂY -> CHUÔNG DING + MỞ KHÓA KẾT QUẢ ---
            if os.path.exists(bell_sound_file):
                try: self.add_sound(bell_sound_file)
                except Exception: pass

            revealed_card = RoundedRectangle(
                corner_radius=0.22,
                width=7.4,
                height=1.42,
                fill_color="#0f172a",
                fill_opacity=1.0,
                stroke_color=lvl_color,
                stroke_width=3.2 if idx < 5 else 4.0
            ).move_to(y_pos)

            # NỬA BÊN TRÁI: Chữ Hán to rõ (font 46 bold), Pinyin (font 24) ở dưới
            hz_mobj = Text(
                hanzi,
                font=CHINESE_FONT,
                font_size=46,
                color="#ffd700" if idx == 5 else WHITE,
                weight=BOLD
            )
            py_mobj = Text(
                f"({{pinyin}})",
                font=VIETNAMESE_FONT,
                font_size=24,
                color="#38bdf8",
                weight="SEMIBOLD"
            )
            left_col = VGroup(hz_mobj, py_mobj).arrange(DOWN, buff=0.08)
            if left_col.width > 3.4:
                left_col.scale_to_fit_width(3.4)
            left_col.move_to(revealed_card.get_left() + RIGHT * 1.95)

            # NỬA BÊN PHẢI: Nghĩa tiếng Việt vàng tươi (font 28 bold)
            mean_mobj = Text(
                meaning_vi,
                font=VIETNAMESE_FONT,
                font_size=28,
                color="#fde047",
                weight=BOLD
            )
            if mean_mobj.width > 3.4:
                mean_mobj.scale_to_fit_width(3.4)
            mean_mobj.move_to(revealed_card.get_right() + LEFT * 1.95)

            active_row_group = VGroup(revealed_card, left_col, mean_mobj)

            # Phát âm tiếng Trung
            if voice_file and os.path.exists(voice_file):
                try: self.add_sound(voice_file)
                except Exception: pass

            # Xóa ô placeholder và hiện kết quả dứt khoát
            self.remove(placeholder_rows[idx - 1])
            self.play(
                FadeIn(active_row_group),
                run_time=0.3
            )
            self.wait(1.4)

        # ---------------------------------------------------------------------
        # 5. END SCREEN OUTRO (00:25 - 00:30) - BỎ TOÀN BỘ CÁC KHUNG/Ô CŨ
        # ---------------------------------------------------------------------
        self.play(
            *[FadeOut(mob) for mob in list(self.mobjects)],
            run_time=0.4
        )
        self.clear()

        # End Screen Card
        end_card = RoundedRectangle(
            corner_radius=0.45,
            width=7.8,
            height=6.6,
            fill_color="#0f172a",
            fill_opacity=0.98,
            stroke_color="#f59e0b",
            stroke_width=2.4
        ).move_to(UP * 0.2)

        # End Screen Channel Logo
        logo_path = "{os.path.join(config.base_dir, 'assets/images/logo.png')}"
        if os.path.exists(logo_path):
            end_logo = ImageMobject(logo_path).set_height(1.6).move_to(end_card.get_top() + DOWN * 1.2)
        else:
            end_logo = Dot(radius=0.6, color="#f59e0b").move_to(end_card.get_top() + DOWN * 1.2)

        end_title = Text(
            "BẠN ĐANG Ở HSK NÀO?",
            font=VIETNAMESE_FONT,
            font_size=40,
            color="#fbbf24",
            weight=BOLD
        ).next_to(end_logo, DOWN, buff=0.35)

        end_cta = Text(
            "Bình luận mốc điểm bạn vượt qua nhé! 👇",
            font=VIETNAMESE_FONT,
            font_size=26,
            color=WHITE,
            weight="SEMIBOLD"
        ).next_to(end_title, DOWN, buff=0.25)

        end_sub = Text(
            "Follow @lelehoctiengtrung để học mỗi ngày 🚀",
            font=VIETNAMESE_FONT,
            font_size=22,
            color="#c4b5fd",
            weight="NORMAL"
        ).next_to(end_cta, DOWN, buff=0.35)

        self.play(
            FadeIn(end_card, shift=UP*0.3),
            FadeIn(end_title, shift=UP*0.2),
            FadeIn(end_cta, shift=UP*0.2),
            FadeIn(end_sub, shift=UP*0.2),
            run_time=0.6
        )
        self.add(end_logo)
        self.wait(3.5)
'''
    return code

def create_scene_file(
    levels: List[Dict[str, Any]],
    concept_name: str,
    hook_title: str,
    output_py_path: str,
    scene_name: str = "MultilevelsQuizScene",
    cover_path: str = "",
    cta_text: str = ""
) -> str:
    """Writes scene code to a .py file and returns the path."""
    os.makedirs(os.path.dirname(output_py_path), exist_ok=True)
    code = generate_scene_code(
        levels=levels,
        concept_name=concept_name,
        hook_title=hook_title,
        scene_name=scene_name,
        cover_path=cover_path,
        cta_text=cta_text
    )
    with open(output_py_path, "w", encoding="utf-8") as f:
        f.write(code)
    return output_py_path
